### ISSUE TITLE
502 http status code on web-site

### ISSUE THREAD

**Issue by maxnag** [zircote/swagger-php#757] opened 2020-02-25 07:33 UTC
When I am trying to reach http://zircote.com/swagger-php/ I have:

DNS error
DNS error (the host name of the page you are looking for does not exist)

Please check that the host name has been spelled correctly.

**Comment by Doqnach** [comment] 2020-02-25 15:26
Duplicate of #751 #740

**Comment by pmediel** [comment] 2020-03-18 21:40
The documentation website is still down

**Comment by youkaihiei** [comment] 2020-03-31 01:42
Looks like its up now.

**Comment by bfanger** [comment] 2020-05-06 21:02
Documentation site has been moved to https://zircote.github.io/swagger-php/

**Closed by bfanger** 2020-05-06 21:02 UTC
