### ISSUE TITLE
Doctrine/dbal problem laravel 6.0 php7

### ISSUE THREAD

**Issue by matheuspaz** [zircote/swagger-php#789] opened 2020-05-28 11:57 UTC
Requiring package using composer, has this error!

**The requested package doctrine/dbal (locked at v2.10.1, required as v2.9.3) is satisfiable by doctrine/dbal[v2.10.1] but these conflict with your requirements or minimum-stability.**

**Comment by DerManoMann** [comment] 2020-05-28 21:38
I take it you are trying to add swagger-php to an existing project?

swagger-php depends on `doctrine/annotations` but doesn't have any requirements on the version so I am not sure how that could cause this error.

Maybe some more details would help? Could you  perhaps provide
a) the `require` block of your composer.json
b) the output of `composer show`
c) the command used to add swagger-php

**Comment by bfanger** [comment] 2020-05-30 10:40
Closing the issue, because swagger-php highly unlikely the caused of this problem.
(we can't fix it with an update)

Feel free to let us know how you solved it, that would help others visiting this issue page

**Closed by bfanger** 2020-05-30 10:40 UTC
