### ISSUE TITLE
problem with opcache.save_comments=0

### ISSUE THREAD

**Issue by drdim** [zircote/swagger-php#357] opened 2017-01-09 05:11 UTC
With this version can get error
{"name":"PHP User Notice","message":"Required @SWG\\Info() not found","code":1024,"type":"yii\\base\\ErrorException","file":"/vagrant/vendor/zircote/swagger-...

On latest version php 7.0.14 without error and generate json normal. Configureation php modules, php.ini - identical.

**Comment by bfanger** [comment] 2017-01-09 15:03
I've upgraded to PHP 7.1.0 and ran the unittests without a problem.

Since the latest swagger-php version, the default is to scan only `*.php` files. other than that i don't know what could be wrong.

Could you investigate what the issue is and provide the offending code-snippet?
Otherwise there is not much i can do.

**Comment by alexeyshockov** [comment] 2017-01-09 15:56
I think it's because swagger-php generates a user notice on 7.1 about `Required @SWG\Info() not found` (don't know why). And [Yii](http://www.yiiframework.com/) wraps this notice into an exception.

@drdim, could you turn off Yii's error handler and check the result again? I think it can help to understand what's wrong. A small notice might not affect the unit tests and the results, but with "fanatic" error handlers it's a problem (that should be fixed, of course).

**Comment by drdim** [comment] 2017-01-10 04:42
If yii_debug sets to false on php 7.1 - i get on generate 500 error. On php7.0.14 work fine.

php 7.1
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT`

if disable all error php.ini:
`{ "swagger": "2.0", "paths": {}, "definitions": {} }`

I think problem with parsing files in structure directories.
invoke scan for me `\Swagger\scan(Yii::getAlias('@api'));`
where @api - folder /vagrant/api

**Comment by drdim** [comment] 2017-01-25 08:39
Problem related with enable option in `opcache.save_comments=0`
if option enable, static files, saved in bite code without comments and parser not found in file Info.
I think add check and exception, if this option enable on client configuration php.

**Closed** 2017-05-20 17:42 UTC

**Comment by bfanger** [comment] 2017-05-20 17:43
swagger-php now checks for if `opcache.save_comments` is set to `false`
