### ISSUE TITLE
Duplicate tags will not be filtered out

### ISSUE THREAD

**Issue by caixingyue** [zircote/swagger-php#1645] opened 2024-08-18 03:28 UTC
I have defined the same tag in different classes. It is recommended to keep only one tag to avoid duplication.

   "tags": [
        {
            "name": "Auth",
            "description": "认证"
        },
        {
            "name": "Other",
            "description": "其它能力"
        },
        {
            "name": "Auth",
            "description": "认证"
        },
        {
            "name": "Auth",
            "description": "认证"
        }
    ]

**Comment by DerManoMann** [comment] 2024-08-18 04:36
Is that using the latest version?

**Comment by caixingyue** [comment] 2024-08-18 05:07
> Is that using the latest version?

Yes, version 4.10.6

**Comment by DerManoMann** [comment] 2024-08-18 06:22
Interesting. Could you post some example annotations to replicate?

**Comment by caixingyue** [comment] 2024-08-18 09:39
> Interesting. Could you post some example annotations to replicate?

Yes, This my config

 $this->processorPipeline = new Pipeline([
                new Processors\DocBlockDescriptions(),
                new Processors\MergeIntoOpenApi(),
                new Processors\MergeIntoComponents(),
                new Processors\ExpandClasses(),
                new Processors\ExpandInterfaces(),
                new Processors\ExpandTraits(),
                new Processors\ExpandEnums(),
                new Processors\AugmentSchemas(),
                new Processors\AugmentRequestBody(),
                new Processors\AugmentProperties(),
                new Processors\BuildPaths(),
                new Processors\AugmentParameters(),
                new Processors\AugmentRefs(),
                new Processors\MergeJsonContent(),
                new Processors\MergeXmlContent(),
                new Processors\OperationId(),
                new Processors\CleanUnmerged(),
                new Processors\PathFilter([], ['/^\/merchant\/.*/']),
                new Processors\CleanUnusedComponents(true),
                new Processors\AugmentTags(),
            ]);

**Comment by DerManoMann** [comment] 2024-08-19 02:46
Sorry for not being clearer - with annotations I meant some of your annotations/attributes where you define those tags?
Ideally a subset that can be used to replicate the bug.

**Comment by caixingyue** [comment] 2024-08-19 06:27
> Sorry for not being clearer - with annotations I meant some of your annotations/attributes where you define those tags? Ideally a subset that can be used to replicate the bug.

I will provide different controllers for different sections, and will also filter them, leaving only one in the end

#[OA\Tag(name: 'Auth', description: '认证')]
class AdminAuthController extends Controller

#[OA\Tag(name: 'Auth', description: '认证')]
class MerchantAuthController extends Controller

**Comment by DerManoMann** [comment] 2024-08-26 04:33
I think there is still not enough to reproduce the issue, unless it is related to the non-english description (sorry I cannot recognize the language).
I would need some complete files that, if processed together, would result in the error. I am asking not to be difficult, but because there are unit tests covering this particular issue (as it has come up before) and therefore if it is a swagger-php issue would be a very edge case.

Having said that there is another issue with how you are using the `Tag` annotation. An explanation can be found here: https://github.com/zircote/swagger-php/issues/1633#issuecomment-2251862566

**Comment by caixingyue** [comment] 2024-08-27 08:18
> I think there is still not enough to reproduce the issue, unless it is related to the non-english description (sorry I cannot recognize the language). I would need some complete files that, if processed together, would result in the error. I am asking not to be difficult, but because there are unit tests covering this particular issue (as it has come up before) and therefore if it is a swagger-php issue would be a very edge case.
> 
> Having said that there is another issue with how you are using the `Tag` annotation. An explanation can be found here: [#1633 (comment)](https://github.com/zircote/swagger-php/issues/1633#issuecomment-2251862566)

I saw your explanation. In your explanation, you managed the tags uniformly.
And I don't manage them uniformly. I define tags for different classes in different php files, so this problem occurs.

But I still think that the same tag may exist for different controller definitions. Because of multi-tenancy, the same functions may exist between different tenants.

**Comment by DerManoMann** [comment] 2024-10-04 00:20
Fair enough. Closing for now as I cannot reproduce the issue with the details given. Feel free to reopen or create a new issue with a complete code sample to reproduce the issue.

**Closed by DerManoMann** 2024-10-04 00:20 UTC
