### ISSUE TITLE
Call to undefined method OpenApi\Generator::setVersion()

### ISSUE THREAD

**Issue by massooti** [zircote/swagger-php#1363] opened 2022-12-14 05:45 UTC
HI there 
i updated my vendor bundle , and then after i wanted to generate a doc via 

```php 
php artisan  l5-swagger:generate
 ```

but it gives me this error 
```php

  Call to undefined method OpenApi\Generator::setVersion()

  at vendor/darkaonline/l5-swagger/src/Generator.php:206
    202▕     {
    203▕         $generator = new OpenApiGenerator();
    204▕ 
    205▕         // OpenApi spec version.
  ➜ 206▕         $generator->setVersion(
    207▕             $this->scanOptions['open_api_spec_version'] ?? self::OPEN_API_DEFAULT_SPEC_VERSION
    208▕         );
    209▕ 
    210▕         // Processors.

      +17 vendor frames 
  18  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

thank you in advanced for any help or advice

**Comment by DerManoMann** [comment] 2022-12-14 07:10
Seems related to https://github.com/DarkaOnLine/L5-Swagger/issues/497

**Comment by DerManoMann** [comment] 2022-12-23 00:49
Closing as caused by https://github.com/DarkaOnLine/L5-Swagger code.

**Closed by DerManoMann** 2022-12-23 00:49 UTC
