### ISSUE TITLE
swagger package cause phpstan error

### ISSUE THREAD

**Issue by zong0828** [zircote/swagger-php#865] opened 2020-10-02 03:26 UTC
As the report, 

https://github.com/nunomaduro/larastan/issues/668

Description
The use of swagger and larastan packages at the same time will cause phpstan analyse error.

```php

[2020-09-27 05:09:53] local.ERROR: AST failed to parse in located source (first 20 characters: <?php

/**
 * ID of ) {"exception":"[object] (_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Exception\\ParseToAstFailure(code: 0): AST failed to parse in located source (first 20 characters: <?php

/**
 * ID of ) at phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Exception/ParseToAstFailure.php:22)
[stacktrace]
#0 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(55): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Exception\\ParseToAstFailure::fromLocatedSource(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(PhpParser\\Error))
#1 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(41): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflectionsOfType(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\IdentifierType))
#2 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(43): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflection(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#3 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AbstractSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#4 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AggregateSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#5 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/Reflector/ConstantReflector.php(34): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\MemoizingSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#6 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(249): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ConstantReflector->reflect('FILTER_UNSAFE_R...')
#7 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(274): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->PHPStan\\Reflection\\BetterReflection\\{closure}('FILTER_UNSAFE_R...')
#8 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(247): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveName(Object(PhpParser\\Node\\Name), Object(Closure), NULL)
#9 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(230): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveConstantName(Object(PhpParser\\Node\\Name), NULL)
#10 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(52): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->getConstant(Object(PhpParser\\Node\\Name), NULL)
#11 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(41): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->getConstant('FILTER_UNSAFE_R...')
#12 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(4035): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->__construct(Object(PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider))
#13 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createService0127()
#14 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('0127')
#15 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(28): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('0127')
#16 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(83): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getService('0127')
#17 [internal function]: PHPStan\\DependencyInjection\\Nette\\NetteContainer->PHPStan\\DependencyInjection\\Nette\\{closure}('0127')
#18 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(84): array_map(Object(Closure), Array)
#19 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(52): PHPStan\\DependencyInjection\\Nette\\NetteContainer->tagsToServices(Array)
#20 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/MemoizingContainer.php(47): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getServicesByTag('phpstan.broker....')
#21 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Analyser/TypeSpecifierFactory.php(24): PHPStan\\DependencyInjection\\MemoizingContainer->getServicesByTag('phpstan.broker....')
#22 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(5945): PHPStan\\Analyser\\TypeSpecifierFactory->create()
#23 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createServiceTypeSpecifier()
#24 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('typeSpecifier')
#25 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php(70): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('typeSpecifier')
#26 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/DerivativeContainerFactory.php(52): PHPStan\\DependencyInjection\\ContainerFactory->create('/var/folders/vm...', Array, Array, Array, Array, Array, '5')
#27 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/PhpDoc/StubValidator.php(67): PHPStan\\DependencyInjection\\DerivativeContainerFactory->create(Array)
#28 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseApplication.php(47): PHPStan\\PhpDoc\\StubValidator->validate()
#29 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseCommand.php(148): PHPStan\\Command\\AnalyseApplication->analyse(Array, false, Object(PHPStan\\Command\\Symfony\\SymfonyOutput), Object(PHPStan\\Command\\Symfony\\SymfonyOutput), false, true, '/Users/zonghan/...', Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput))
#30 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Command/Command.php(228): PHPStan\\Command\\AnalyseCommand->execute(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(852): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Command\\Command->run(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(235): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRunCommand(Object(PHPStan\\Command\\AnalyseCommand), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(136): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRun(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(76): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->run()
#35 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(77): _HumbugBox37da87c0ed2f\\{closure}()
#36 /Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan(6): require('phar:///Users/z...')
#37 {main}

[previous exception] [object] (PhpParser\\Error(code: 0): Syntax error, unexpected ',' on line 7 on unknown line at phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Parser/PhpParserDecorator.php:25)
[stacktrace]
#0 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(53): PHPStan\\Parser\\PhpParserDecorator->parse('<?php\
\
/**\
 * I...')
#1 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Locator.php(41): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflectionsOfType(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\IdentifierType))
#2 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(43): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Ast\\Locator->findReflection(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Located\\InternalLocatedSource), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#3 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/AggregateSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AbstractSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#4 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Type/MemoizingSourceLocator.php(31): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\AggregateSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#5 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/Reflector/ConstantReflector.php(34): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\SourceLocator\\Type\\MemoizingSourceLocator->locateIdentifier(Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ClassReflector), Object(_HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Identifier\\Identifier))
#6 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(249): _HumbugBox37da87c0ed2f\\Roave\\BetterReflection\\Reflector\\ConstantReflector->reflect('FILTER_UNSAFE_R...')
#7 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(274): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->PHPStan\\Reflection\\BetterReflection\\{closure}('FILTER_UNSAFE_R...')
#8 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(247): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveName(Object(PhpParser\\Node\\Name), Object(Closure), NULL)
#9 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Reflection/BetterReflection/BetterReflectionProvider.php(230): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->resolveConstantName(Object(PhpParser\\Node\\Name), NULL)
#10 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(52): PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider->getConstant(Object(PhpParser\\Node\\Name), NULL)
#11 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Type/Php/FilterVarDynamicReturnTypeExtension.php(41): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->getConstant('FILTER_UNSAFE_R...')
#12 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(4035): PHPStan\\Type\\Php\\FilterVarDynamicReturnTypeExtension->__construct(Object(PHPStan\\Reflection\\BetterReflection\\BetterReflectionProvider))
#13 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createService0127()
#14 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('0127')
#15 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(28): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('0127')
#16 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(83): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getService('0127')
#17 [internal function]: PHPStan\\DependencyInjection\\Nette\\NetteContainer->PHPStan\\DependencyInjection\\Nette\\{closure}('0127')
#18 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(84): array_map(Object(Closure), Array)
#19 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/Nette/NetteContainer.php(52): PHPStan\\DependencyInjection\\Nette\\NetteContainer->tagsToServices(Array)
#20 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/MemoizingContainer.php(47): PHPStan\\DependencyInjection\\Nette\\NetteContainer->getServicesByTag('phpstan.broker....')
#21 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Analyser/TypeSpecifierFactory.php(24): PHPStan\\DependencyInjection\\MemoizingContainer->getServicesByTag('phpstan.broker....')
#22 /private/var/folders/vm/xt8_93f91qxb319cskfgdvzh0000gn/T/phpstan/cache/nette.configurator/Container_1d2dbb4858.php(5945): PHPStan\\Analyser\\TypeSpecifierFactory->create()
#23 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(157): Container_1d2dbb4858->createServiceTypeSpecifier()
#24 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/nette/di/src/DI/Container.php(90): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->createService('typeSpecifier')
#25 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/ContainerFactory.php(70): _HumbugBox37da87c0ed2f\\Nette\\DI\\Container->getService('typeSpecifier')
#26 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/DependencyInjection/DerivativeContainerFactory.php(52): PHPStan\\DependencyInjection\\ContainerFactory->create('/var/folders/vm...', Array, Array, Array, Array, Array, '5')
#27 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/PhpDoc/StubValidator.php(67): PHPStan\\DependencyInjection\\DerivativeContainerFactory->create(Array)
#28 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseApplication.php(47): PHPStan\\PhpDoc\\StubValidator->validate()
#29 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/src/Command/AnalyseCommand.php(148): PHPStan\\Command\\AnalyseApplication->analyse(Array, false, Object(PHPStan\\Command\\Symfony\\SymfonyOutput), Object(PHPStan\\Command\\Symfony\\SymfonyOutput), false, true, '/Users/zonghan/...', Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput))
#30 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Command/Command.php(228): PHPStan\\Command\\AnalyseCommand->execute(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#31 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(852): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Command\\Command->run(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#32 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(235): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRunCommand(Object(PHPStan\\Command\\AnalyseCommand), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#33 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/vendor/symfony/console/Application.php(136): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->doRun(Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Input\\ArgvInput), Object(_HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Output\\ConsoleOutput))
#34 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(76): _HumbugBox37da87c0ed2f\\Symfony\\Component\\Console\\Application->run()
#35 phar:///Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan/bin/phpstan(77): _HumbugBox37da87c0ed2f\\{closure}()
#36 /Users/zonghan/Applications/dev-backend/source-code/msg/vendor/phpstan/phpstan/phpstan(6): require('phar:///Users/z...')
#37 {main}
"} 


```

**Comment by robbplo** [comment] 2020-10-06 07:30
I'm having a similar issue in a project I'm working on, except the error is less descriptive:

```
$ vendor/bin/phpstan analyse
Note: Using configuration file /Users/robbinploeger/projects/hsa-api/phpstan.neon.dist.

In StubPhpDocProvider.php line 150:
                   
  Internal error.

```

Tried to reproduce it in a fresh repository: https://github.com/robbplo/swagger-larastan
However, i can run `vendor/bin/openapi app` **and** `vendor/bin/phpstan analyse` without issues there...

**Comment by Doqnach** [comment] 2020-10-06 08:00
So the problem might exist in code outside of larastan and swagger-php?

@zong0828 `Syntax error, unexpected ',' on line 7 on unknown line` seems to tell me you have some trailing comma somewhere in a PHPDOC of your own code (so not Swagger-PHP related)?

**Comment by robbplo** [comment] 2020-10-06 10:21
I forgot to mention that when i `composer remove zircote/swagger-php` in my original project phpstan works like a charm, with swagger annotations still in the codebase. I'm still trying to reproduce this behaviour in the previously linked repository, as the project I'm working on is for a client.

**Comment by DerManoMann** [comment] 2020-10-06 20:11
@robbplo Thanks for spending time on this - without a way to reproduce this there is little to be done...

**Comment by robbplo** [comment] 2020-10-07 13:28
Turns out it was caused by phpstan: https://github.com/phpstan/phpstan/issues/3885

It's fixed in phpstan 0.12.46, and it's working after I updated my composer.lock.

Feel free to close!

**Comment by Doqnach** [comment] 2020-10-07 17:10
@robbplo happy your problem is solved. This issue though started because of a different issue that seems unrelated to that of @robbplo, but we have not heard back from @zong0828 yet.

**Comment by robbplo** [comment] 2020-10-07 17:54
Of course, I was a little overzealous 😅 

I did manage to get the same error as @zong0828 while debugging today, again in https://github.com/robbplo/swagger-larastan.

After cloning the repo and installing composer dependencies, I modified `vendor/zircote/swagger-php/src/functions.php`. After commenting out line 23 it looks like this:
```
// PHP 8.0
if (!defined('T_NAME_QUALIFIED')) {
    //define('T_NAME_QUALIFIED', -4);
}
if (!defined('T_NAME_FULLY_QUALIFIED')) {
    define('T_NAME_FULLY_QUALIFIED', -5);
}
```

Then running `vendor/bin/phpstan analyse --debug` I get the following output:

```
Note: Using configuration file /Users/robbinploeger/projects/swagger-test/phpstan.neon.dist.
PHPStan crashed in the previous run probably because of excessive memory consumption.
It consumed around 43 MB of memory.


To avoid this issue, allow to use more memory with the --memory-limit option.

   _HumbugBox10beb0db089e\Roave\BetterReflection\SourceLocator\Ast\Exception\ParseToAstFailure 

  AST failed to parse in located source (first 20 characters: <?php

/**
 * ID of )

  at phar://vendor/phpstan/phpstan/phpstan/vendor/ondrejmirtes/better-reflection/src/SourceLocator/Ast/Exception/ParseToAstFailure.php:22
    18|         }
    19|         if ($additionalInformation === '') {
    20|             $additionalInformation = \sprintf(' (first 20 characters: %s)', \substr($locatedSource->getSource(), 0, 20));
    21|         }
  > 22|         return new self(\sprintf('AST failed to parse in located source%s', $additionalInformation), 0, $previous);
    23|     }
    24| }
    25| 

      +1 vendor frames 
  2   [internal]:0
      PHPStan\DependencyInjection\Nette\NetteContainer::PHPStan\DependencyInjection\Nette\{closure}("0125")

      +13 vendor frames 
  16  /private/var/folders/l0/m00kz9p17ygfw6y33f5b_jfw0000gn/T/phpstan/cache/nette.configurator/Container_bc0b2d1bd4.php:3993
      PHPStan\Type\Php\FilterVarDynamicReturnTypeExtension::__construct(Object(PHPStan\Reflection\BetterReflection\BetterReflectionProvider))
```

Hope this helps in finding the cause of the original issue

**Comment by DerManoMann** [comment] 2020-10-10 02:50
Feels to me there will be some compatibility issues while libraries upgrade their code to support PHP8.

I wonder what conditional code is tied to the existence (or not) of the `T_NAME_QUALIFIED` const.....

**Comment by DerManoMann** [comment] 2020-10-26 21:52
Just had a couple spare minutes and cloned the repo - running phpstan right after a `composer install` gives me
```
$ vendor/bin/phpstan analyse --debug
Note: Using configuration file ./swagger-larastan/phpstan.neon.dist.

   PHPStan\ShouldNotHappenException 

  Internal error.

  at phar://vendor/phpstan/phpstan/phpstan/src/PhpDoc/StubPhpDocProvider.php:150
    146|     }
    147|     private function initializeKnownElements() : void
    148|     {
    149|         if ($this->initializing) {
  > 150|             throw new \PHPStan\ShouldNotHappenException();
    151|         }
    152|         if ($this->initialized) {
    153|             return;
    154|         }
```

is that expected?

**Comment by DerManoMann** [comment] 2021-01-07 03:33
Feels like this has been a transient issue while lots of libraries were upgrading for PHP8 and some polifills didn't like to play with each other.
Closing for now unless someone comes with a reliable reproducer.

**Closed by DerManoMann** 2021-01-07 03:33 UTC
