### ISSUE TITLE
Notice versioning system in readme.md 

### ISSUE THREAD

**Issue by kverfaille** [zircote/swagger-php#385] opened 2017-03-24 10:01 UTC
Hi guys,

During the last release (2.0.8 to 2.0.9) I noticed this change "Added support for PHP 7.1 and dropped support for PHP 5.5 and below". Not that nowadays anyone should be affected by this, but it scares me a bit that a release drops functionality for such a minor update. Off course I don't know if this was caused by hard to solve or unsolvable conflicts (This could be an exception on the general practice), hence I have this request to explain the versioning rules on the index page (readme.md)? 

I ask this so I can safely put a version in my composer file that only adds functionality & fixes.

Thanks in advance!

**Comment by bfanger** [comment] 2017-03-24 10:06
Duplicate of #374 & #367

**Comment by kverfaille** [comment] 2017-03-24 11:02
Agree, I had to take a closer look on the closed ones ...

Maybe next time when such change is done, mention it in the commit message/release notes as a non-breaking change with a small explanation. This way you can avoid message duplicates as mine :-)... Srry about that!

**Comment by bfanger** [comment] 2017-03-24 11:06
It's nice to see that the changelog gets so much attention.
Thanks for the tip.

**Closed by bfanger** 2017-03-24 11:06 UTC
