### ISSUE TITLE
How to upload multiple files within the same parameter

### ISSUE THREAD

**Issue by sjorskamphuis** [zircote/swagger-php#535] opened 2018-06-08 13:13 UTC
# How to upload multiple files within the same parameter?

At this moment it looks like it isn't allowed to upload multiple files within the same parameter (like an array with some files).

```php
<?php
    /**
     * @SWG\Parameter(
     *          name="files",
     *          type="array",
     *          in="formData",
     *          required=true,
     *          @SWG\Items(
     *              type="file",
     *              @SWG\Parameter(
     *                  name="avatar",
     *                  type="file",
     *                  in="formData",
     *              ),
     *          )
     *     ),
     */
```

**Comment by bfanger** [comment] 2018-08-08 15:25
Duplicate of #525

**Closed** 2018-09-30 12:15 UTC
