### ISSUE TITLE
Propose ordering for API documentation on Swagger UI

### ISSUE THREAD

**Issue by sonoftheweb** [zircote/swagger-php#611] opened 2018-11-12 10:40 UTC
Propose ordering for API documentation on Swagger UI. When creating API docs, we should be able to add "order"=int where int is a number. This number should be used to order the API endpoints in Swagger UI as in my case, some actions needs to be made before some other actions can be tested. Pray tell if there is a way to already do this.

**Comment by bfanger** [comment] 2018-11-15 18:17
Duplicate of #478

**Comment by bfanger** [comment] 2018-11-16 11:09
There is no build in ways to do this. But you can add a vendor `@OA\Thing(x={"order":1}` and then write a [processor](https://github.com/zircote/swagger-php/tree/master/src/Processors)  to sort the annotations based on those values.

If you decide to create such plugin, i'll gladly link to it from the [related projects](http://zircote.com/swagger-php/Related-projects.html) page

**Closed by bfanger** 2018-11-16 11:09 UTC
